app_name: Rails eCommerce

user:
  name_max_len: 100
  pwd_min_len: 6
  email_max_len: 100
  phone_max_len: 20
 
product:
  img_max_size: 200
  per_page: 8
  img_max_size_cart: 50

order:
  per_page: 6
  shipping_cost_default: 40000

category:
  img_max_size: 100

date_format: "%d/%m/%Y %H:%M"
receive_report_email: duchkhe140530@fpt.edu.vn
